-- Fix admin password hash
-- This migration ensures the admin password hash is correct for 'thiyen1'
-- BCrypt hash generated by Spring Boot BCryptPasswordEncoder

UPDATE users 
SET password = '$2a$10$7kxU4rihoD/1EQIQUgwnyeikUE/b7demo0i/DVE8HEstp2UJka07a'
WHERE username = 'admin';

-- If admin user doesn't exist, create it
INSERT INTO users (username, password, email, role) 
VALUES ('admin', '$2a$10$7kxU4rihoD/1EQIQUgwnyeikUE/b7demo0i/DVE8HEstp2UJka07a', 'admin@thiyen.com', 'ROLE_ADMIN')
ON CONFLICT (username) DO UPDATE 
SET password = EXCLUDED.password,
    email = EXCLUDED.email,
    role = EXCLUDED.role;

