spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ecommerce}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
  
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  
  flyway:
    enabled: true
    validate-on-migrate: false

server:
  port: 5678

logging:
  level:
    root: INFO
    com.dragun.ecommerce: DEBUG
    org.springframework.security: WARN
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF


